# All user input is string by default
string_variable = input("Input a string: ")
int_variable = int(input("Input an int: "))
float_variable = float(input("Input a float: "))
boolean_variable = eval(input("Input a boolean: "))
print()
print("string_variable type:", type(string_variable))
print("int_variable type:", type(int_variable))
print("float_variable type:", type(float_variable))
print("boolean_variable type:", type(boolean_variable))
